indexers:
  -
    name: newznab1
    host: http://127.0.0.1:5000
    apikey: a
    searchModuleType: newznab
    supportedSearchIds: TVRAGE
    score: 1
  -
    name: newznab2
    host: http://127.0.0.1:5000
    apikey: b
    searchModuleType: newznab
    supportedSearchIds: IMDB, TMDB
    score: 2
#  -
#    name: newznab3
#    host: http://127.0.0.1:5000
#    apikey: c
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab4
#    host: http://127.0.0.1:5000
#    apikey: d
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab5
#    host: http://127.0.0.1:5000
#    apikey: e
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab6
#    host: http://127.0.0.1:5000
#    apikey: f
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab7
#    host: http://127.0.0.1:5000
#    apikey: g
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab8
#    host: http://127.0.0.1:5000
#    apikey: h
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab9
#    host: http://127.0.0.1:5000
#    apikey: i
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab10
#    host: http://127.0.0.1:5000
#    apikey: j
#    searchModuleType: newznab
#    score: 1
categories:
  -
    name: n/a
    pretty: N/A
    newznabCategories:
  -
    name: all
    pretty: All
    newznabCategories:
    mayBeSelected: true
    ignoreResults: NONE
  -
    name: category1
    newznabCategories: 1000,2000
    pretty: category1
    mayBeSelected: true
    ignoreResults: NONE
  -
    name: category2
    newznabCategories: 3000,4000
    pretty: category2
    mayBeSelected: true
    ignoreResults: NONE

spring:
  datasource:
    url: jdbc:hsqldb:file:nzbhydra.db
    #url: jdbc:hsqldb:hsql://localhost:9001/xdb;shutdown=true
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver

logging:
  level:
    org:
      nzbhydra: DEBUG

server:
  contextPath: / #Set for reverse proxy support