auth:
  authType: NONE
  rememberUsers: true
  restrictAdmin: true
  restrictDetailsDl: true
  restrictIndexerSelection: true
  restrictSearch: true
  restrictStats: true
  users:
  - maySeeAdmin: true
    maySeeDetailsDl: true
    maySeeStats: true
    password: a
    showIndexerSelection: true
    username: a
  - maySeeAdmin: false
    maySeeDetailsDl: false
    maySeeStats: false
    password: u
    showIndexerSelection: false
    username: u
  - maySeeAdmin: false
    maySeeDetailsDl: true
    maySeeStats: true
    password: s
    showIndexerSelection: true
    username: s

downloaders:
    -
        defaultCategory: No category
        downloadType: nzb
        enabled: true
        iconCssClass: ''
        name: nzbget
        nzbAddingType: SEND_LINK
        nzbaccesstype: PROXY
        downloaderType: NZBGET
        url: http://127.0.0.1:6789/
    -
        apikey: 63e1c248a4a84c63e44b5a2ce9153cfe
        defaultCategory: No category
        downloadType: nzb
        enabled: true
        iconCssClass: ''
        name: SABnzbd
        nzbAddingType: SEND_LINK
        nzbaccesstype: PROXY
        downloaderType: SABNZBD
        url: http://127.0.0.1:8085/sabnzbd/
#- downloadType: nzb
#  enabled: false
#  host: 127.0.0.1
#  iconCssClass: ''
#  name: NZBGet2
#  nzbAddingType: link
#  nzbaccesstype: serve
#  password: tegbzn6789x
#  port: 6789
#  ssl: false
#  type: nzbget
#  username: nzbgetx
#- downloadType: nzb
#  enabled: false
#  host: 127.0.0.1
#  iconCssClass: ''
#  name: NZBGet4
#  nzbAddingType: link
#  nzbaccesstype: redirect
#  password: tegbzn6789x
#  port: 6789
#  ssl: false
#  type: nzbget
#  username: nzbgetx

indexers:
  -
    name: newznab1
    host: http://127.0.0.1:5000
    enabled: true
    apikey: a
    searchModuleType: NEWZNAB
    supportedSearchIds: TVRAGE
    score: 1
    enabledForSearchSource: BOTH
  -
    name: newznab2
    host: http://127.0.0.1:5000
    enabled: true
    apikey: b
    hitLimitResetTime: 12
    searchModuleType: NEWZNAB
    supportedSearchIds: IMDB, TMDB
    score: 2
    enabledForSearchSource: BOTH
  -
    name: newznab3
    host: http://invalid
    enabled: true
    apikey: c
    searchModuleType: NEWZNAB
    score: 1
    enabledForSearchSource: BOTH
  -
    name: newznab4
    host: http://127.0.0.1:5000
    enabled: true
    apikey: d
    searchModuleType: NEWZNAB
    score: 1
    enabledForSearchSource: BOTH
#  -
#    name: newznab5
#    host: http://127.0.0.1:5000
#    enabled: true
#    apikey: e
#    searchModuleType: newznab
#    score: 1
#    enabledForSearchSource: API
#  -
#    name: newznab6
#    host: http://127.0.0.1:5000
#    apikey: f
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab7
#    host: http://127.0.0.1:5000
#    apikey: g
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab8
#    host: http://127.0.0.1:5000
#    apikey: h
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab9
#    host: http://127.0.0.1:5000
#    apikey: i
#    searchModuleType: newznab
#    score: 1
#  -
#    name: newznab10
#    host: http://127.0.0.1:5000
#    apikey: j
#    searchModuleType: newznab
#    score: 1
categories:
  -
    name: n/a
    pretty: N/A
    newznabCategories:
    ignoreResultsFrom: NONE
    applyRestrictionsType: NONE
  -
    name: all
    pretty: All
    newznabCategories:
    mayBeSelected: true
    ignoreResultsFrom: NONE
    applyRestrictionsType: NONE
    enableCategorySizes: false
  -
    name: category1
    newznabCategories: 1000,2000
    pretty: category1
    mayBeSelected: true
    ignoreResultsFrom: NONE
    applyRestrictionsType: NONE
    enableCategorySizes: false
  -
    name: movies
    newznabCategories: 3000,4000
    pretty: Movies
    mayBeSelected: true
    ignoreResultsFrom: NONE
    applyRestrictionsType: NONE
    enableCategorySizes: false


main:
  apiKey: apikey
  branch: develop
  configVersion: 1
  debug: true
  dereferer: http://www.dereferer.org/?$s
  externalUrl: ''
  #firstStart: null
  gitPath: c:\Program Files (x86)\Git\bin\git.exe
  host: 127.0.0.1
  httpProxy:
  httpsProxy:
  isFirstStart: false
  keepSearchResultsForDays: 7
  logging:
    consolelevel: DEBUG
    keepLogFiles: 25
    logIpAddresses: true
    logMaxSize: 1000
    logRotateAfterDays:
    logfilelevel: DEBUG
    logfilename: nzbhydra.log
    rolloverAtStart: false
  port: 5076
  repositoryBase: https://github.com/theotherp
  runThreaded: true
  secret: 6UH5FZH8VI4KQ5H1
  shutdownForRestart: true
  socksProxy: ''
  ssl: false
  sslcert: nzbhydra.crt
  sslkey: nzbhydra.key
  startupBrowser: false
  theme: grey
  urlBase: ''
  useCsrf: true
  useLocalUrlForApiAccess: true


searching:
  alwaysShowDuplicates: true
  applyRestrictions: BOTH
  categorySettings: {}
  duplicateAgeThreshold: 2
  duplicateSizeThresholdInPercent: 1
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: ''
  forbiddenWords: 'title200'
  generateQueries: []
  idFallbackToTitle: NONE
  idFallbackToTitlePerIndexer: false
  ignorePassworded: true
  ignoreTemporarilyDisabled: true
  maxAge: null
  nzbAccessType: redirect
  removeLanguage: true
  removeObfuscated: false
  requiredRegex: ''
  requiredWords: []
  timeout: 20
  userAgent: Chrome





spring:
  datasource:
    url: jdbc:hsqldb:file:nzbhydra.db;shutdown=true;
    #url: jdbc:hsqldb:hsql://localhost:9001/xdb;shutdown=true
#    username: sa
#    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver




logging:
  level:
    org:
      nzbhydra: DEBUG

