# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/repo

    environment:
      - MAVEN_OPTS: -Xmx3200m
      - PHANTOMJSBIN: /usr/local/bin/phantomjs
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      #Clean install all but without integration tests
      - run: mvn -pl "!org.nzbhydra:tests" clean install dependency:resolve-plugins dependency:go-offline

      #Run integration tests
      - run: mvn -f tests/pom.xml verify

      #Collect all surefire reports and put them in one folder for Circle to parse
      - run: mkdir -p ~/junit/
      - run: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
      - run: find . -type f -regex ".*/target/screenshots/.*png" -exec cp {} ~/junit/ \;
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit