# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn -pl "!org.nzbhydra:linux-release,!org.nzbhydra:windows-release" -DskipTests=true clean install dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: .
          paths: .

  unit-test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn -f main/pom.xml -fae -DreportsDirectory=allSurefireReports test

      - store_test_results:
          path: /home/circleci/repo/main/core/target/surefire-reports

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build