---
auth:
  authType: "NONE"
  rememberUsers: true
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  users: []
categoriesConfig:
    enableCategorySizes: true
    categories:
        - name: Anime
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 3000
          minSizePreset: 50
          newznabCategories:
          - 5070
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
        - name: Audio
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 2000
          minSizePreset: 1
          newznabCategories:
          - 3000
          requiredRegex:
          requiredWords: ["mp3", "flac"]
          preselect: true
          searchType: MUSIC
        - name: Audiobook
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 1000
          minSizePreset: 50
          newznabCategories:
          - 3030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
        - name: Comic
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 250
          minSizePreset: 1
          newznabCategories:
          - 7030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
        - name: Console
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 40000
          minSizePreset: 100
          newznabCategories:
          - 1000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
        - name: Ebook
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 100
          minSizePreset:
          newznabCategories:
          - 7020
          - 8010
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
        - name: FLAC
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 2000
          minSizePreset: 10
          newznabCategories:
          - 3040
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
        - name: Movies
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 20000
          minSizePreset: 500
          newznabCategories:
          - 2000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
        - name: Movies HD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 20000
          minSizePreset: 3000
          newznabCategories:
          - 2040
          - 2050
          - 2060
          - 2070
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
        - name: Movies SD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 3000
          minSizePreset: 500
          newznabCategories:
          - 2030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MOVIE
        - name: MP3
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 500
          minSizePreset: 1
          newznabCategories:
          - 3000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: MUSIC
        - name: PC
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 50000
          minSizePreset: 100
          newznabCategories:
          - 4000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
        - name: TV
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 5000
          minSizePreset: 50
          newznabCategories:
          - 5000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
        - name: TV HD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 4500
          minSizePreset: 300
          newznabCategories:
          - 5040
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
        - name: TV SD
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 1000
          minSizePreset: 50
          newznabCategories:
          - 5030
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: TVSEARCH
        - name: XXX
          applyRestrictionsType: BOTH
          forbiddenRegex:
          forbiddenWords:
          ignoreResultsFrom: NONE
          maxSizePreset: 10000
          minSizePreset: 100
          newznabCategories:
          - 6000
          requiredRegex:
          requiredWords:
          preselect: true
          searchType: SEARCH
downloaders: []
indexers: []
main:
  apiKey: null
  branch: "master"
  configVersion: 1
  debug: false
  dereferer: null
  externalUrl: null
  firstStart: false
  gitPath: null
  host: "0.0.0.0"
  httpProxy: null
  httpsProxy: null
  logging:
    consolelevel: "DEBUG"
    keepLogFiles: 25
    logIpAddresses: true
    logMaxSize: 1000
    logRotateAfterDays: null
    logfilelevel: "DEBUG"
    logfilename: "nzbhydra.log"
    rolloverAtStart: false
  keepSearchResultsForDays: 7
  port: 5076
  repositoryBase: "https://github.com/theotherp"
  secret: "TODO generate"
  shutdownForRestart: false
  socksProxy: null
  ssl: false
  sslcert: null
  sslkey: null
  startupBrowser: true
  theme: "grey"
  updateCheckEnabled: true
  urlBase: "/"
  useCsrf: true
  useLocalUrlForApiAccess: true
searching:
  alwaysShowDuplicates: false
  applyRestrictions: "NONE"
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  enableCategorySizes: true
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  generateQueries: "NONE"
  idFallbackToTitle: "NONE"
  idFallbackToTitlePerIndexer: false
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  maxAge: null
  nzbAccessType: "REDIRECT"
  removeLanguage: false
  removeObfuscated: false
  requiredRegex: null
  requiredWords: []
  timeout: 20
  userAgent: "NZBHydra"
  wrapApiErrors: false