indexers: []
categories:
  -
    name: n/a
    pretty: N/A
    newznabCategories:
  -
    name: all
    pretty: All
    newznabCategories:
    mayBeSelected: true
    ignoreResults: NONE
  -
    name: category1
    newznabCategories: 1000,2000
    pretty: category1
    mayBeSelected: true
    ignoreResults: NONE
  -
    name: category2
    newznabCategories: 3000,4000
    pretty: category2
    mayBeSelected: true
    ignoreResults: NONE


main:
  apiKey:
  baseUrl: /
  configVersion: 1
  debug: false
  externalUrl:
  host: 0.0.0.0

spring:
  datasource:
    url: jdbc:hsqldb:file:nzbhydra.db
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver



