indexers: []
categories: []

main:
  apiKey:
  baseUrl: /
  configVersion: 1
  debug: false
  externalUrl:
  host: 0.0.0.0
  useCsrf: true

spring:
  datasource:
    url: jdbc:hsqldb:file:nzbhydra.db;shutdown=true;
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
